/**
 * RouteMap — MapLibre GL map with offline MBTiles vector tile base layer,
 * route polyline, hotspot checkpoint markers, direction dots,
 * start/end markers, map labels, and live user position.
 *
 * CRITICAL RULES (breaking any of these kills the map silently):
 *  - Base style layers: ONLY fill/line/background. NO symbol layers in base style.
 *  - NO standalone layers without parent ShapeSource.
 *  - Hotspot/start/end markers use MarkerView (native RN views) — works offline.
 *  - Map labels use ShapeSource + SymbolLayer with LOCAL bundled glyph PBFs
 *    (asset://glyphs/{fontstack}/{range}.pbf) — fully offline, GPU-rendered.
 *  - Map geometry overlays use ShapeSource + LineLayer/CircleLayer.
 */

import { useEffect, useMemo, useRef, useState } from 'react';
import { StyleSheet, View, Platform, ActivityIndicator, Text, Pressable } from 'react-native';
import { Asset } from 'expo-asset';

import { Brand, RouteColors, Spacing } from '@/constants/theme';
import { ThemedText } from '@/components/themed-text';
import type { Hotspot, UserLocation } from '@/src/types';

// MapLibre is native-only — guarded by Platform check at render time.
let MapLibreGL: typeof import('@maplibre/maplibre-react-native');
if (Platform.OS !== 'web') {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  MapLibreGL = require('@maplibre/maplibre-react-native');
}

// Pre-extracted map labels (12K+ features: place names, roads, water, POIs, peaks)
// Generated by: node scripts/extract-labels.js
// Rendered via SymbolLayer (GPU) with locally bundled glyph PBFs — fully offline
let mapLabelsGeoJSON: GeoJSON.FeatureCollection | null = null;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  mapLabelsGeoJSON = require('../src/data/map-labels.json');
} catch {
  console.warn('RouteMap: map-labels.json not found — labels will not render');
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface RouteMapProps {
  routeCoords: [number, number][];
  hotspots: Hotspot[];
  unlockedHotspotIds: Set<string>;
  visitedHotspotIds: Set<string>;
  currentLocation: UserLocation | null;
  onHotspotPress: (hotspot: Hotspot) => void;
}

// ---------------------------------------------------------------------------
// MBTiles asset loader
// ---------------------------------------------------------------------------

// eslint-disable-next-line @typescript-eslint/no-require-imports
const MBTILES_MODULE = require('../assets/campania.mbtiles');

async function loadStyle(): Promise<Record<string, unknown> | null> {
  try {
    const asset = Asset.fromModule(MBTILES_MODULE);
    await asset.downloadAsync();
    if (!asset.localUri) return null;
    const mbtilesPath = asset.localUri.replace(/^file:\/\//, '');

    return {
      version: 8,
      sources: {
        campania: {
          type: 'vector',
          url: `mbtiles://${mbtilesPath}`,
        },
      },
      // LOCAL glyph PBFs bundled in android/app/src/main/assets/glyphs/
      // Downloaded from fonts.openmaptiles.org — works fully offline
      glyphs: 'asset://glyphs/{fontstack}/{range}.pbf',
      layers: [
        { id: 'background', type: 'background',
          paint: { 'background-color': '#F2EFE9' } },
        { id: 'landcover', type: 'fill', source: 'campania',
          'source-layer': 'landcover',
          paint: { 'fill-color': '#C8DFA0', 'fill-opacity': 0.45 } },
        { id: 'landuse', type: 'fill', source: 'campania',
          'source-layer': 'landuse',
          paint: { 'fill-color': '#E0D8D0', 'fill-opacity': 0.35 } },
        { id: 'park', type: 'fill', source: 'campania',
          'source-layer': 'park',
          paint: { 'fill-color': '#B0D490', 'fill-opacity': 0.5 } },
        { id: 'water', type: 'fill', source: 'campania',
          'source-layer': 'water',
          paint: { 'fill-color': '#88C4E0' } },
        { id: 'waterway', type: 'line', source: 'campania',
          'source-layer': 'waterway',
          paint: { 'line-color': '#88C4E0', 'line-width': 1.5 } },
        { id: 'building', type: 'fill', source: 'campania',
          'source-layer': 'building',
          paint: { 'fill-color': '#D4C8BC', 'fill-opacity': 0.5 } },
        { id: 'boundary', type: 'line', source: 'campania',
          'source-layer': 'boundary',
          paint: { 'line-color': '#9E7B9B', 'line-width': 1 } },
        { id: 'road', type: 'line', source: 'campania',
          'source-layer': 'transportation',
          paint: { 'line-color': '#FFFFFF', 'line-width': 2 } },
        { id: 'aeroway', type: 'line', source: 'campania',
          'source-layer': 'aeroway',
          paint: { 'line-color': '#D0CFCB', 'line-width': 4 } },
      ],
    };
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function computeBounds(coords: [number, number][]): {
  ne: [number, number]; sw: [number, number];
} {
  let minLng = Infinity, maxLng = -Infinity, minLat = Infinity, maxLat = -Infinity;
  for (const [lng, lat] of coords) {
    if (lng < minLng) minLng = lng;
    if (lng > maxLng) maxLng = lng;
    if (lat < minLat) minLat = lat;
    if (lat > maxLat) maxLat = lat;
  }
  return { ne: [maxLng, maxLat], sw: [minLng, minLat] };
}

function hotspotColor(
  hs: Hotspot, unlockedIds: Set<string>, visitedIds: Set<string>,
): string {
  if (unlockedIds.has(hs.id)) return RouteColors.hotspotActive;
  if (visitedIds.has(hs.id)) return RouteColors.hotspotVisited;
  if (hs.isActive) return RouteColors.hotspotLocked;
  return RouteColors.hotspotWaypoint;
}

function haversineM(
  [lng1, lat1]: [number, number], [lng2, lat2]: [number, number],
): number {
  const R = 6371000;
  const toRad = Math.PI / 180;
  const dLat = (lat2 - lat1) * toRad;
  const dLng = (lng2 - lng1) * toRad;
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1 * toRad) * Math.cos(lat2 * toRad) * Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

function sampleDirectionDots(
  coords: [number, number][], intervalM: number,
): GeoJSON.Feature[] {
  if (coords.length < 2) return [];
  const dots: GeoJSON.Feature[] = [];
  let accumulated = 0;
  for (let i = 1; i < coords.length; i++) {
    accumulated += haversineM(coords[i - 1], coords[i]);
    if (accumulated >= intervalM) {
      accumulated = 0;
      dots.push({
        type: 'Feature', properties: {},
        geometry: { type: 'Point', coordinates: coords[i] },
      });
    }
  }
  return dots;
}

// ---------------------------------------------------------------------------
// Marker sub-components — native RN views for hotspots/start/end (works offline)
// ---------------------------------------------------------------------------

function StartMarker({ coordinate }: { coordinate: [number, number] }) {
  if (!MapLibreGL) return null;
  return (
    <MapLibreGL.MarkerView coordinate={coordinate} anchor={{ x: 0.5, y: 0.5 }}>
      <View style={markerStyles.startEnd}>
        <View style={[markerStyles.startEndCircle, { backgroundColor: '#27AE60' }]}>
          <Text style={markerStyles.startEndText}>P</Text>
        </View>
        <Text style={markerStyles.startEndLabel}>Partenza</Text>
      </View>
    </MapLibreGL.MarkerView>
  );
}

function EndMarker({ coordinate }: { coordinate: [number, number] }) {
  if (!MapLibreGL) return null;
  return (
    <MapLibreGL.MarkerView coordinate={coordinate} anchor={{ x: 0.5, y: 0.5 }}>
      <View style={markerStyles.startEnd}>
        <View style={[markerStyles.startEndCircle, { backgroundColor: '#E74C3C' }]}>
          <Text style={markerStyles.startEndText}>A</Text>
        </View>
        <Text style={markerStyles.startEndLabel}>Arrivo</Text>
      </View>
    </MapLibreGL.MarkerView>
  );
}

function HotspotMarker({
  hotspot, color, isUnlocked, onPress,
}: {
  hotspot: Hotspot; color: string; isUnlocked: boolean;
  onPress: (hs: Hotspot) => void;
}) {
  if (!MapLibreGL) return null;
  const size = isUnlocked ? 32 : hotspot.isActive ? 26 : 22;
  return (
    <MapLibreGL.MarkerView
      coordinate={[hotspot.longitude, hotspot.latitude]}
      anchor={{ x: 0.5, y: 0.5 }}
    >
      <Pressable style={markerStyles.hotspotContainer} onPress={() => onPress(hotspot)}>
        <View style={[markerStyles.hotspotCircle, {
          backgroundColor: color,
          borderColor: isUnlocked ? '#FFFFFF' : '#666666',
          width: size, height: size, borderRadius: size / 2,
        }]}>
          <Text style={[markerStyles.hotspotSeq, { fontSize: isUnlocked ? 14 : 11 }]}>
            {hotspot.sequence}
          </Text>
        </View>
        <Text style={markerStyles.hotspotTitle} numberOfLines={2}>
          {hotspot.title}
        </Text>
      </Pressable>
    </MapLibreGL.MarkerView>
  );
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function RouteMap({
  routeCoords, hotspots, unlockedHotspotIds, visitedHotspotIds,
  currentLocation, onHotspotPress,
}: RouteMapProps) {
  const [mapStyle, setMapStyle] = useState<Record<string, unknown> | null>(null);
  const [loading, setLoading] = useState(true);
  const cameraRef = useRef<any>(null);

  useEffect(() => {
    let cancelled = false;
    loadStyle().then((style) => {
      if (cancelled) return;
      if (style) setMapStyle(style);
      setLoading(false);
    });
    return () => { cancelled = true; };
  }, []);

  const routeGeoJSON = useMemo(
    (): GeoJSON.FeatureCollection => ({
      type: 'FeatureCollection',
      features: routeCoords.length > 0 ? [{
        type: 'Feature', properties: {},
        geometry: { type: 'LineString', coordinates: routeCoords },
      }] : [],
    }),
    [routeCoords],
  );

  const directionDotsGeoJSON = useMemo(
    (): GeoJSON.FeatureCollection => ({
      type: 'FeatureCollection',
      features: routeCoords.length >= 2 ? sampleDirectionDots(routeCoords, 300) : [],
    }),
    [routeCoords],
  );

  const bounds = useMemo(() => {
    if (routeCoords.length === 0) return null;
    return computeBounds(routeCoords);
  }, [routeCoords]);

  const userGeoJSON = useMemo((): GeoJSON.FeatureCollection | null => {
    if (!currentLocation) return null;
    return {
      type: 'FeatureCollection',
      features: [{
        type: 'Feature',
        properties: { accuracy: currentLocation.accuracy },
        geometry: {
          type: 'Point',
          coordinates: [currentLocation.longitude, currentLocation.latitude],
        },
      }],
    };
  }, [currentLocation]);

  const fallbackStyle = useMemo(() => ({
    version: 8, sources: {},
    glyphs: 'asset://glyphs/{fontstack}/{range}.pbf',
    layers: [{ id: 'background', type: 'background',
      paint: { 'background-color': '#E8EDF2' } }],
  }), []);

  if (Platform.OS === 'web' || !MapLibreGL) {
    return (
      <View style={styles.fallback}>
        <ThemedText style={styles.fallbackText}>
          Map is available on iOS & Android
        </ThemedText>
      </View>
    );
  }

  if (loading) {
    return (
      <View style={styles.fallback}>
        <ActivityIndicator size="large" color={Brand.primary} />
        <ThemedText style={styles.fallbackText}>Loading offline map…</ThemedText>
      </View>
    );
  }

  const activeStyle = mapStyle ?? fallbackStyle;
  const startCoord = routeCoords.length >= 2 ? routeCoords[0] : null;
  const endCoord = routeCoords.length >= 2 ? routeCoords[routeCoords.length - 1] : null;

  return (
    <MapLibreGL.MapView
      style={styles.map}
      mapStyle={activeStyle}
      logoEnabled={false}
      attributionEnabled={false}
      compassEnabled
      compassViewMargins={{ x: 16, y: 100 }}
    >
      {bounds && (
        <MapLibreGL.Camera
          ref={cameraRef}
          defaultSettings={{
            bounds: {
              ne: bounds.ne, sw: bounds.sw,
              paddingTop: 80, paddingBottom: 200,
              paddingLeft: 40, paddingRight: 40,
            },
          }}
          animationDuration={0}
        />
      )}

      {/* ── Map labels — SymbolLayer with LOCAL offline glyph PBFs ── */}
      {/* All 12K+ labels (places, roads, water, POIs, peaks) rendered by GPU */}
      {mapLabelsGeoJSON && (
        <MapLibreGL.ShapeSource id="labels-source" shape={mapLabelsGeoJSON}>
          {/* City labels — large bold */}
          <MapLibreGL.SymbolLayer
            id="label-city"
            filter={['all', ['==', ['get', 'type'], 'place'], ['==', ['get', 'class'], 'city']]}
            style={{
              textField: ['get', 'name'],
              textFont: ['OpenSansBold'],
              textSize: 16,
              textColor: '#1a1a1a',
              textHaloColor: '#FFFFFF',
              textHaloWidth: 2,
              textAllowOverlap: false,
              textMaxWidth: 10,
            }}
          />
          {/* Town labels — medium bold */}
          <MapLibreGL.SymbolLayer
            id="label-town"
            filter={['all', ['==', ['get', 'type'], 'place'], ['==', ['get', 'class'], 'town']]}
            style={{
              textField: ['get', 'name'],
              textFont: ['OpenSansBold'],
              textSize: 13,
              textColor: '#333333',
              textHaloColor: '#FFFFFF',
              textHaloWidth: 1.5,
              textAllowOverlap: false,
              textMaxWidth: 8,
            }}
          />
          {/* Village labels */}
          <MapLibreGL.SymbolLayer
            id="label-village"
            filter={['all', ['==', ['get', 'type'], 'place'], ['==', ['get', 'class'], 'village']]}
            style={{
              textField: ['get', 'name'],
              textFont: ['OpenSansRegular'],
              textSize: 11,
              textColor: '#444444',
              textHaloColor: '#FFFFFF',
              textHaloWidth: 1.5,
              textAllowOverlap: false,
              textMaxWidth: 8,
            }}
          />
          {/* Hamlet / suburb / neighbourhood / other place labels */}
          <MapLibreGL.SymbolLayer
            id="label-hamlet"
            filter={['all', ['==', ['get', 'type'], 'place'],
              ['!', ['in', ['get', 'class'], ['literal', ['city', 'town', 'village']]]]]}
            style={{
              textField: ['get', 'name'],
              textFont: ['OpenSansRegular'],
              textSize: 9,
              textColor: '#666666',
              textHaloColor: '#FFFFFF',
              textHaloWidth: 1,
              textAllowOverlap: false,
              textMaxWidth: 7,
            }}
          />
          {/* Road labels */}
          <MapLibreGL.SymbolLayer
            id="label-road"
            filter={['==', ['get', 'type'], 'road']}
            style={{
              textField: ['get', 'name'],
              textFont: ['OpenSansRegular'],
              textSize: 9,
              textColor: '#666666',
              textHaloColor: '#FFFFFF',
              textHaloWidth: 1,
              textAllowOverlap: false,
              textMaxWidth: 10,
              symbolPlacement: 'point',
            }}
          />
          {/* Water labels */}
          <MapLibreGL.SymbolLayer
            id="label-water"
            filter={['==', ['get', 'type'], 'water']}
            style={{
              textField: ['get', 'name'],
              textFont: ['OpenSansRegular'],
              textSize: 11,
              textColor: '#2171A5',
              textHaloColor: '#FFFFFF',
              textHaloWidth: 1.5,
              textAllowOverlap: false,
              textMaxWidth: 8,
            }}
          />
          {/* Peak labels */}
          <MapLibreGL.SymbolLayer
            id="label-peak"
            filter={['==', ['get', 'type'], 'peak']}
            style={{
              textField: ['get', 'name'],
              textFont: ['OpenSansRegular'],
              textSize: 10,
              textColor: '#8B4513',
              textHaloColor: '#FFFFFF',
              textHaloWidth: 1,
              textAllowOverlap: false,
              textMaxWidth: 8,
            }}
          />
          {/* POI labels */}
          <MapLibreGL.SymbolLayer
            id="label-poi"
            filter={['==', ['get', 'type'], 'poi']}
            style={{
              textField: ['get', 'name'],
              textFont: ['OpenSansRegular'],
              textSize: 9,
              textColor: '#555555',
              textHaloColor: '#FFFFFF',
              textHaloWidth: 1,
              textAllowOverlap: false,
              textMaxWidth: 7,
            }}
          />
        </MapLibreGL.ShapeSource>
      )}

      {/* ── Route polyline ── */}
      <MapLibreGL.ShapeSource id="route-source" shape={routeGeoJSON}>
        <MapLibreGL.LineLayer
          id="route-line-casing"
          style={{
            lineColor: '#FFFFFF',
            lineWidth: RouteColors.routeLineWidth + 2,
            lineJoin: 'round', lineCap: 'round',
          }}
        />
        <MapLibreGL.LineLayer
          id="route-line"
          style={{
            lineColor: RouteColors.routeLine,
            lineWidth: RouteColors.routeLineWidth,
            lineJoin: 'round', lineCap: 'round',
          }}
        />
      </MapLibreGL.ShapeSource>

      {/* ── Direction dots along route ── */}
      <MapLibreGL.ShapeSource id="dots-source" shape={directionDotsGeoJSON}>
        <MapLibreGL.CircleLayer
          id="direction-dots"
          style={{
            circleRadius: 4,
            circleColor: '#1A5A96',
            circleStrokeColor: '#FFFFFF',
            circleStrokeWidth: 1.5,
          }}
        />
      </MapLibreGL.ShapeSource>

      {/* ── User location dot ── */}
      {userGeoJSON && (
        <MapLibreGL.ShapeSource id="user-location-source" shape={userGeoJSON}>
          <MapLibreGL.CircleLayer
            id="user-accuracy"
            style={{
              circleRadius: 20,
              circleColor: RouteColors.userDot + '20',
              circleStrokeColor: RouteColors.userDot + '40',
              circleStrokeWidth: 1,
            }}
          />
          <MapLibreGL.CircleLayer
            id="user-dot"
            style={{
              circleRadius: 8,
              circleColor: RouteColors.userDot,
              circleStrokeColor: '#FFFFFF',
              circleStrokeWidth: 3,
            }}
          />
        </MapLibreGL.ShapeSource>
      )}

      {/* ── Hotspot checkpoint markers (native RN views) ── */}
      {hotspots.map((hs) => (
        <HotspotMarker
          key={hs.id}
          hotspot={hs}
          color={hotspotColor(hs, unlockedHotspotIds, visitedHotspotIds)}
          isUnlocked={unlockedHotspotIds.has(hs.id)}
          onPress={onHotspotPress}
        />
      ))}

      {/* ── Start marker — green "P" (Partenza) ── */}
      {startCoord && <StartMarker coordinate={startCoord} />}

      {/* ── End marker — red "A" (Arrivo) ── */}
      {endCoord && <EndMarker coordinate={endCoord} />}
    </MapLibreGL.MapView>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const markerStyles = StyleSheet.create({
  startEnd: {
    alignItems: 'center', justifyContent: 'center',
  },
  startEndCircle: {
    width: 36, height: 36, borderRadius: 18,
    borderWidth: 3, borderColor: '#FFFFFF',
    alignItems: 'center', justifyContent: 'center',
    elevation: 5,
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3, shadowRadius: 3,
  },
  startEndText: {
    color: '#FFFFFF', fontSize: 16, fontWeight: 'bold',
  },
  startEndLabel: {
    fontSize: 10, color: '#333', fontWeight: 'bold',
    backgroundColor: 'rgba(255,255,255,0.85)',
    paddingHorizontal: 4, paddingVertical: 1, borderRadius: 3,
    marginTop: 2, overflow: 'hidden',
  },
  hotspotContainer: {
    alignItems: 'center', maxWidth: 100,
  },
  hotspotCircle: {
    borderWidth: 2, alignItems: 'center', justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2, shadowRadius: 2,
  },
  hotspotSeq: {
    color: '#FFFFFF', fontWeight: 'bold',
  },
  hotspotTitle: {
    fontSize: 10, color: '#333333', textAlign: 'center',
    marginTop: 2, backgroundColor: 'rgba(255,255,255,0.8)',
    paddingHorizontal: 4, paddingVertical: 1, borderRadius: 3, overflow: 'hidden',
  },
});

const styles = StyleSheet.create({
  map: { flex: 1 },
  fallback: {
    flex: 1, justifyContent: 'center', alignItems: 'center',
    backgroundColor: '#E8EDF2', gap: Spacing.sm,
  },
  fallbackText: { fontSize: 14, color: Brand.gray500 },
});
