/**
 * RouteMap — MapLibre GL map with offline MBTiles vector tile base layer,
 * route polyline, hotspot checkpoint markers, direction dots,
 * start/end markers, map labels, and live user position.
 *
 * CRITICAL RULES (breaking any of these kills the map silently):
 *  - Base style layers: ONLY fill/line/background. NO symbol layers.
 *  - NO standalone layers without parent ShapeSource.
 *  - NO SymbolLayer at all — glyphs need internet, app is offline.
 *  - ALL text/markers rendered via MarkerView (native RN views).
 *  - Map geometry overlays use ShapeSource + LineLayer/CircleLayer only.
 */

import { useEffect, useMemo, useRef, useState } from 'react';
import { StyleSheet, View, Platform, ActivityIndicator, Text } from 'react-native';
import { Asset } from 'expo-asset';

import { Brand, RouteColors, Spacing } from '@/constants/theme';
import { ThemedText } from '@/components/themed-text';
import type { Hotspot, UserLocation } from '@/src/types';

// MapLibre is native-only — guarded by Platform check at render time.
let MapLibreGL: typeof import('@maplibre/maplibre-react-native');
if (Platform.OS !== 'web') {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  MapLibreGL = require('@maplibre/maplibre-react-native');
}

// Pre-extracted map labels — only important ones rendered as native views
// Generated by: node scripts/extract-labels.js
let mapLabelsGeoJSON: GeoJSON.FeatureCollection | null = null;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  mapLabelsGeoJSON = require('../src/data/map-labels.json');
} catch {
  console.warn('RouteMap: map-labels.json not found — labels will not render');
}

// Filter labels to only the most important ones for MarkerView rendering
// (MarkerView = real RN views, so we limit count for performance)
interface MapLabel {
  name: string;
  type: string;
  class?: string;
  rank?: number;
  coordinate: [number, number];
  fontSize: number;
  color: string;
  bold: boolean;
}

function buildAllLabels(): MapLabel[] {
  if (!mapLabelsGeoJSON) return [];
  const labels: MapLabel[] = [];

  for (const f of mapLabelsGeoJSON.features) {
    const p = f.properties;
    if (!p || !p.name) continue;
    const coords = (f.geometry as GeoJSON.Point).coordinates as [number, number];

    let fontSize = 10;
    let color = '#444444';
    let bold = false;

    if (p.type === 'place') {
      if (p.class === 'city') { fontSize = 16; color = '#1a1a1a'; bold = true; }
      else if (p.class === 'town') { fontSize = 13; color = '#333333'; bold = true; }
      else if (p.class === 'village') { fontSize = 11; color = '#444444'; }
      else if (p.class === 'suburb' || p.class === 'quarter') { fontSize = 10; color = '#555555'; }
      else { fontSize = 9; color = '#666666'; } // hamlet, neighbourhood, isolated_dwelling
    } else if (p.type === 'water') {
      fontSize = 11; color = '#2171A5';
    } else if (p.type === 'peak') {
      fontSize = 10; color = '#8B4513';
    } else if (p.type === 'road') {
      if (p.class === 'motorway' || p.class === 'trunk' || p.class === 'primary') {
        fontSize = 10; color = '#666666'; bold = true;
      } else if (p.class === 'secondary' || p.class === 'tertiary') {
        fontSize = 9; color = '#777777';
      } else {
        fontSize = 8; color = '#888888';
      }
    } else if (p.type === 'poi') {
      fontSize = 9; color = '#555555';
    }

    const name = p.type === 'peak' && p.ele ? `${p.name} ${p.ele}m` : p.name;

    labels.push({ name, type: p.type, class: p.class, rank: p.rank,
      coordinate: coords, fontSize, color, bold });
  }

  return labels;
}

const allLabels = buildAllLabels();

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface RouteMapProps {
  routeCoords: [number, number][];
  hotspots: Hotspot[];
  unlockedHotspotIds: Set<string>;
  visitedHotspotIds: Set<string>;
  currentLocation: UserLocation | null;
  onHotspotPress: (hotspot: Hotspot) => void;
}

// ---------------------------------------------------------------------------
// MBTiles asset loader
// ---------------------------------------------------------------------------

// eslint-disable-next-line @typescript-eslint/no-require-imports
const MBTILES_MODULE = require('../assets/campania.mbtiles');

async function loadStyle(): Promise<Record<string, unknown> | null> {
  try {
    const asset = Asset.fromModule(MBTILES_MODULE);
    await asset.downloadAsync();
    if (!asset.localUri) return null;
    const mbtilesPath = asset.localUri.replace(/^file:\/\//, '');

    return {
      version: 8,
      sources: {
        campania: {
          type: 'vector',
          url: `mbtiles://${mbtilesPath}`,
        },
      },
      // Glyphs URL kept for potential future use but NO SymbolLayers reference it
      glyphs: 'https://demotiles.maplibre.org/font/{fontstack}/{range}.pbf',
      layers: [
        // TEMP: pink background — if you see pink, the JS bundle updated.
        // Change back to #F2EFE9 after confirming.
        { id: 'background', type: 'background',
          paint: { 'background-color': '#FF69B4' } },
        { id: 'landcover', type: 'fill', source: 'campania',
          'source-layer': 'landcover',
          paint: { 'fill-color': '#C8DFA0', 'fill-opacity': 0.45 } },
        { id: 'landuse', type: 'fill', source: 'campania',
          'source-layer': 'landuse',
          paint: { 'fill-color': '#E0D8D0', 'fill-opacity': 0.35 } },
        { id: 'park', type: 'fill', source: 'campania',
          'source-layer': 'park',
          paint: { 'fill-color': '#B0D490', 'fill-opacity': 0.5 } },
        { id: 'water', type: 'fill', source: 'campania',
          'source-layer': 'water',
          paint: { 'fill-color': '#88C4E0' } },
        { id: 'waterway', type: 'line', source: 'campania',
          'source-layer': 'waterway',
          paint: { 'line-color': '#88C4E0', 'line-width': 1.5 } },
        { id: 'building', type: 'fill', source: 'campania',
          'source-layer': 'building',
          paint: { 'fill-color': '#D4C8BC', 'fill-opacity': 0.5 } },
        { id: 'boundary', type: 'line', source: 'campania',
          'source-layer': 'boundary',
          paint: { 'line-color': '#9E7B9B', 'line-width': 1 } },
        { id: 'road', type: 'line', source: 'campania',
          'source-layer': 'transportation',
          paint: { 'line-color': '#FFFFFF', 'line-width': 2 } },
        { id: 'aeroway', type: 'line', source: 'campania',
          'source-layer': 'aeroway',
          paint: { 'line-color': '#D0CFCB', 'line-width': 4 } },
      ],
    };
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function computeBounds(coords: [number, number][]): {
  ne: [number, number];
  sw: [number, number];
} {
  let minLng = Infinity, maxLng = -Infinity, minLat = Infinity, maxLat = -Infinity;
  for (const [lng, lat] of coords) {
    if (lng < minLng) minLng = lng;
    if (lng > maxLng) maxLng = lng;
    if (lat < minLat) minLat = lat;
    if (lat > maxLat) maxLat = lat;
  }
  return { ne: [maxLng, maxLat], sw: [minLng, minLat] };
}

function hotspotColor(
  hs: Hotspot, unlockedIds: Set<string>, visitedIds: Set<string>,
): string {
  if (unlockedIds.has(hs.id)) return RouteColors.hotspotActive;
  if (visitedIds.has(hs.id)) return RouteColors.hotspotVisited;
  if (hs.isActive) return RouteColors.hotspotLocked;
  return RouteColors.hotspotWaypoint;
}

function haversineM(
  [lng1, lat1]: [number, number], [lng2, lat2]: [number, number],
): number {
  const R = 6371000;
  const toRad = Math.PI / 180;
  const dLat = (lat2 - lat1) * toRad;
  const dLng = (lng2 - lng1) * toRad;
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1 * toRad) * Math.cos(lat2 * toRad) * Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

function sampleDirectionDots(
  coords: [number, number][], intervalM: number,
): GeoJSON.Feature[] {
  if (coords.length < 2) return [];
  const dots: GeoJSON.Feature[] = [];
  let accumulated = 0;
  for (let i = 1; i < coords.length; i++) {
    accumulated += haversineM(coords[i - 1], coords[i]);
    if (accumulated >= intervalM) {
      accumulated = 0;
      dots.push({
        type: 'Feature',
        properties: {},
        geometry: { type: 'Point', coordinates: coords[i] },
      });
    }
  }
  return dots;
}

// ---------------------------------------------------------------------------
// Marker sub-components — ALL use native RN views (no glyphs, works offline)
// ---------------------------------------------------------------------------

function StartMarker({ coordinate }: { coordinate: [number, number] }) {
  if (!MapLibreGL) return null;
  return (
    <MapLibreGL.MarkerView coordinate={coordinate} anchor={{ x: 0.5, y: 0.5 }}>
      <View style={markerStyles.startEnd}>
        <View style={[markerStyles.startEndCircle, { backgroundColor: '#27AE60' }]}>
          <Text style={markerStyles.startEndText}>P</Text>
        </View>
        <Text style={markerStyles.startEndLabel}>Partenza</Text>
      </View>
    </MapLibreGL.MarkerView>
  );
}

function EndMarker({ coordinate }: { coordinate: [number, number] }) {
  if (!MapLibreGL) return null;
  return (
    <MapLibreGL.MarkerView coordinate={coordinate} anchor={{ x: 0.5, y: 0.5 }}>
      <View style={markerStyles.startEnd}>
        <View style={[markerStyles.startEndCircle, { backgroundColor: '#E74C3C' }]}>
          <Text style={markerStyles.startEndText}>A</Text>
        </View>
        <Text style={markerStyles.startEndLabel}>Arrivo</Text>
      </View>
    </MapLibreGL.MarkerView>
  );
}

function HotspotMarker({
  hotspot, color, isUnlocked, onPress,
}: {
  hotspot: Hotspot; color: string; isUnlocked: boolean;
  onPress: (hs: Hotspot) => void;
}) {
  if (!MapLibreGL) return null;
  const size = isUnlocked ? 32 : hotspot.isActive ? 26 : 22;
  return (
    <MapLibreGL.MarkerView
      coordinate={[hotspot.longitude, hotspot.latitude]}
      anchor={{ x: 0.5, y: 0.5 }}
    >
      <View style={markerStyles.hotspotContainer} onTouchEnd={() => onPress(hotspot)}>
        <View style={[markerStyles.hotspotCircle, {
          backgroundColor: color,
          borderColor: isUnlocked ? '#FFFFFF' : '#666666',
          width: size, height: size, borderRadius: size / 2,
        }]}>
          <Text style={[markerStyles.hotspotSeq, { fontSize: isUnlocked ? 14 : 11 }]}>
            {hotspot.sequence}
          </Text>
        </View>
        <Text style={markerStyles.hotspotTitle} numberOfLines={2}>
          {hotspot.title}
        </Text>
      </View>
    </MapLibreGL.MarkerView>
  );
}

function MapLabelMarker({ label }: { label: MapLabel }) {
  if (!MapLibreGL) return null;
  return (
    <MapLibreGL.MarkerView
      coordinate={label.coordinate}
      anchor={{ x: 0.5, y: 0.5 }}
      allowOverlap={false}
    >
      <Text style={[
        markerStyles.mapLabel,
        {
          fontSize: label.fontSize,
          color: label.color,
          fontWeight: label.bold ? 'bold' : 'normal',
        },
      ]}>
        {label.name}
      </Text>
    </MapLibreGL.MarkerView>
  );
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function RouteMap({
  routeCoords, hotspots, unlockedHotspotIds, visitedHotspotIds,
  currentLocation, onHotspotPress,
}: RouteMapProps) {
  const [mapStyle, setMapStyle] = useState<Record<string, unknown> | null>(null);
  const [loading, setLoading] = useState(true);
  const cameraRef = useRef<any>(null);

  useEffect(() => {
    let cancelled = false;
    loadStyle().then((style) => {
      if (cancelled) return;
      if (style) setMapStyle(style);
      setLoading(false);
    });
    return () => { cancelled = true; };
  }, []);

  const routeGeoJSON = useMemo(
    (): GeoJSON.FeatureCollection => ({
      type: 'FeatureCollection',
      features: routeCoords.length > 0 ? [{
        type: 'Feature', properties: {},
        geometry: { type: 'LineString', coordinates: routeCoords },
      }] : [],
    }),
    [routeCoords],
  );

  const directionDotsGeoJSON = useMemo(
    (): GeoJSON.FeatureCollection => ({
      type: 'FeatureCollection',
      features: routeCoords.length >= 2 ? sampleDirectionDots(routeCoords, 300) : [],
    }),
    [routeCoords],
  );

  const bounds = useMemo(() => {
    if (routeCoords.length === 0) return null;
    return computeBounds(routeCoords);
  }, [routeCoords]);

  const userGeoJSON = useMemo((): GeoJSON.FeatureCollection | null => {
    if (!currentLocation) return null;
    return {
      type: 'FeatureCollection',
      features: [{
        type: 'Feature',
        properties: { accuracy: currentLocation.accuracy },
        geometry: {
          type: 'Point',
          coordinates: [currentLocation.longitude, currentLocation.latitude],
        },
      }],
    };
  }, [currentLocation]);

  const fallbackStyle = useMemo(() => ({
    version: 8, sources: {},
    layers: [{ id: 'background', type: 'background',
      paint: { 'background-color': '#FF69B4' } }],
  }), []);

  if (Platform.OS === 'web' || !MapLibreGL) {
    return (
      <View style={styles.fallback}>
        <ThemedText style={styles.fallbackText}>
          Map is available on iOS & Android
        </ThemedText>
      </View>
    );
  }

  if (loading) {
    return (
      <View style={styles.fallback}>
        <ActivityIndicator size="large" color={Brand.primary} />
        <ThemedText style={styles.fallbackText}>Loading offline map…</ThemedText>
      </View>
    );
  }

  const activeStyle = mapStyle ?? fallbackStyle;
  const startCoord = routeCoords.length >= 2 ? routeCoords[0] : null;
  const endCoord = routeCoords.length >= 2 ? routeCoords[routeCoords.length - 1] : null;

  return (
    <MapLibreGL.MapView
      style={styles.map}
      mapStyle={activeStyle}
      logoEnabled={false}
      attributionEnabled={false}
      compassEnabled
      compassViewMargins={{ x: 16, y: 100 }}
    >
      {bounds && (
        <MapLibreGL.Camera
          ref={cameraRef}
          defaultSettings={{
            bounds: {
              ne: bounds.ne, sw: bounds.sw,
              paddingTop: 80, paddingBottom: 200,
              paddingLeft: 40, paddingRight: 40,
            },
          }}
          animationDuration={0}
        />
      )}

      {/* Route polyline */}
      <MapLibreGL.ShapeSource id="route-source" shape={routeGeoJSON}>
        <MapLibreGL.LineLayer
          id="route-line-casing"
          style={{
            lineColor: '#FFFFFF',
            lineWidth: RouteColors.routeLineWidth + 2,
            lineJoin: 'round', lineCap: 'round',
          }}
        />
        <MapLibreGL.LineLayer
          id="route-line"
          style={{
            lineColor: RouteColors.routeLine,
            lineWidth: RouteColors.routeLineWidth,
            lineJoin: 'round', lineCap: 'round',
          }}
        />
      </MapLibreGL.ShapeSource>

      {/* Direction dots along route — CircleLayer, no glyphs */}
      <MapLibreGL.ShapeSource id="dots-source" shape={directionDotsGeoJSON}>
        <MapLibreGL.CircleLayer
          id="direction-dots"
          style={{
            circleRadius: 4,
            circleColor: '#1A5A96',
            circleStrokeColor: '#FFFFFF',
            circleStrokeWidth: 1.5,
          }}
        />
      </MapLibreGL.ShapeSource>

      {/* User location dot */}
      {userGeoJSON && (
        <MapLibreGL.ShapeSource id="user-location-source" shape={userGeoJSON}>
          <MapLibreGL.CircleLayer
            id="user-accuracy"
            style={{
              circleRadius: 20,
              circleColor: RouteColors.userDot + '20',
              circleStrokeColor: RouteColors.userDot + '40',
              circleStrokeWidth: 1,
            }}
          />
          <MapLibreGL.CircleLayer
            id="user-dot"
            style={{
              circleRadius: 8,
              circleColor: RouteColors.userDot,
              circleStrokeColor: '#FFFFFF',
              circleStrokeWidth: 3,
            }}
          />
        </MapLibreGL.ShapeSource>
      )}

      {/* Map labels — ALL labels as native RN Text views, fully offline */}
      {allLabels.map((label, i) => (
        <MapLabelMarker key={`label-${label.type}-${i}`} label={label} />
      ))}

      {/* Hotspot checkpoint markers */}
      {hotspots.map((hs) => (
        <HotspotMarker
          key={hs.id}
          hotspot={hs}
          color={hotspotColor(hs, unlockedHotspotIds, visitedHotspotIds)}
          isUnlocked={unlockedHotspotIds.has(hs.id)}
          onPress={onHotspotPress}
        />
      ))}

      {/* Start marker — green "P" (Partenza) */}
      {startCoord && <StartMarker coordinate={startCoord} />}

      {/* End marker — red "A" (Arrivo) */}
      {endCoord && <EndMarker coordinate={endCoord} />}
    </MapLibreGL.MapView>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const markerStyles = StyleSheet.create({
  startEnd: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  startEndCircle: {
    width: 36, height: 36, borderRadius: 18,
    borderWidth: 3, borderColor: '#FFFFFF',
    alignItems: 'center', justifyContent: 'center',
    elevation: 5,
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3, shadowRadius: 3,
  },
  startEndText: {
    color: '#FFFFFF', fontSize: 16, fontWeight: 'bold',
  },
  startEndLabel: {
    fontSize: 10, color: '#333', fontWeight: 'bold',
    backgroundColor: 'rgba(255,255,255,0.85)',
    paddingHorizontal: 4, paddingVertical: 1, borderRadius: 3,
    marginTop: 2, overflow: 'hidden',
  },
  hotspotContainer: {
    alignItems: 'center', maxWidth: 100,
  },
  hotspotCircle: {
    borderWidth: 2, alignItems: 'center', justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2, shadowRadius: 2,
  },
  hotspotSeq: {
    color: '#FFFFFF', fontWeight: 'bold',
  },
  hotspotTitle: {
    fontSize: 10, color: '#333333', textAlign: 'center',
    marginTop: 2, backgroundColor: 'rgba(255,255,255,0.8)',
    paddingHorizontal: 4, paddingVertical: 1, borderRadius: 3, overflow: 'hidden',
  },
  mapLabel: {
    textShadowColor: '#FFFFFF',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
});

const styles = StyleSheet.create({
  map: { flex: 1 },
  fallback: {
    flex: 1, justifyContent: 'center', alignItems: 'center',
    backgroundColor: '#E8EDF2', gap: Spacing.sm,
  },
  fallbackText: { fontSize: 14, color: Brand.gray500 },
});
